name: webtoon_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.18.1
  mailer: ^6.1.0
  serverpod: 2.0.0
  serverpod_auth_server: 2.0.0
  serverpod_serialization: 2.0.0

dev_dependencies:
  lints: ^3.0.0
