name: webtoon_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  get: 4.6.6
  serverpod_flutter: 1.2.6
  webtoon_client:
    path: ../webtoon_client

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
