name: webtoon_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project with Serverpod.
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: 4.6.6
  minio:
    git:
      url: https://github.com/anoochit/minio-dart.git
  serverpod_auth_email_flutter: 2.0.0-alpha.2
  serverpod_auth_shared_flutter: 2.0.0-alpha.2
  serverpod_flutter: 2.0.0-alpha.2
  webtoon_client:
    path: ../webtoon_client

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
